export const MAX_LENGTH_IDENTITY = 12;
export const MAX_LENGTH_PHONE = 10;
export const MAX_LENGTH_JOB = 30;
export const MAX_LENGTH_COMPANY = 30;
export const MAX_LENGTH_PERMANANT_ADDRESS = 50;
export const MAX_LENGTH_FIRST_NAME = 30;
export const MAX_LENGTH_LAST_NAME = 30;
export const MAX_LENGTH_MONEY_INPUT = 15;
export const MAX_LENGTH_RATE_INPUT = 5;
export const MAX_LENGTH_MONTH_INPUT = 3;
export const MAX_LENGTH_YEAR_INPUT = 4; // năm  bắt đầu làm việc
export const MAX_LENGTH_STREET_ADDRESS = 150;
export const DEFAULT_CURRENCY_UNIT = 'VND';
export const DEFAULT_CURRENCY_UNIT_ID = 7; // VND
export const MAX_UPLOAD_FILE_SIZE = 5242880;
export const MAX_UPLOAD_FILE_SIZE_TEXT = '5MB';
export const MAX_LENGTH_PACKAGE_NAME = 150;
export const MAX_LENGTH_PACKAGE_DESCRIPTION = 500;
export const MAX_LENGTH_OTP = 10;
export const MAX_DESIRED_AMOUNT = 100000000000;
export const MAX_MONTH_DURATION = 480;  // Thời gian tối đa (tháng)
export const ACCEPT_IMAGE_TYPES = 'image/png,image/jpeg,image/jpe';
export const ACCEPT_EXCEL_TYPES = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-excel, application/vnd.ms-excel.sheet.macroEnabled.12';
export const ACCEPT_ALL_TYPES = 'application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/pdf, image/png, image/jpeg, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet';
export const DEFAULT_TABLE_PAGE_SIZE = 20;  // Số dòng tối đa trong 1 page của Table
